### ISSUE TITLE
Segregate files

### ISSUE THREAD

**Issue by americast** [kossiitkgp/kossiitkgp.github.io#9]
All semantic-ui related files have been combined into one as `/semantic-ui/semantic.css`. They need to be segregated into multiple files, each corresponding to various elements of the UI, just like in the **initial commit**.

**Comment by djbarnwal** [comment]
Is this really required ? We are going to use most of the components throughout the website. So lets say a user visits the homepage, here if we add the minified version of whole Semantics CSS then it will be stored in the users cache. Now when the users visits other pages of the website, the browser does not has to make request for the CSS file again. 
Secondly it will be very confusing for new developers to decide which files to import for a particular class tag. In order to optimize the whole thing what we can do is that we normally use `semantic.css` while developing the website and during the finishing period we can at once remove all unused css. Further we can compress the css file for maximum optimization.

**Comment by americast** [comment]
@dhiraj161298 I think this is necessary. Themes are provided only in modularised fashion. Hence it would be easy to make modifications if we have things divided. Moreover, editing the framework would be very difficult in the current form. It is also very difficult to understand diff in just one file. Also, diff between the original files and this is also difficult to trace. You can still use `semantic.css` as one in all by importing all other stuff into it.
> Now when the users visits other pages of the website, the browser does not has to make request for the CSS file again.

We could leverage browser caching, for sometime, say around 10 minutes ..?
> during the finishing period we can at once remove all unused css :+1: 

I guess combining all these stuff into one should have been done only during the finishing period.

**Comment by americast** [comment]
Closing this now. May be reopened later when theme changes are requested.
